HotcakesCommerce/hotcakes-commerce-core

Libraries/Hotcakes.Commerce.Dnn/Utils/MvcUtils.cs
Added logic to prevent Hotcakes view engine from being added to the collection multiple times. Resolves issue #7
=> Resolve Source array was not long enough Issue

Build.proj, CommonAssemblyInfo.cs, WebDeploy/Build.proj, Website/DesktopModules/Hotcakes/Hotcakes.dnn
Version number updates and resolving an introduced build conflict update.
=> Updates preparing for the v03.00.01 release

Libraries/Hotcakes.Commerce/WebAppSettings.System.cs
=> Removing the SKU from the footer in the admin views to resolve issue #16

DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/Category/_Header.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/Products/_Rating.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/Category/_Header.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/Products/_Rating.cshtml
Removed social code references from sample viewsets to resolve issue #55
=> Resolves issue #55

DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/Products/_Rating.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/Products/_Rating.cshtml, Website/DesktopModules/Hotcakes/Core/Admin/Configuration/App_LocalResources/ProductReviews.aspx.resx, Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Products/_Rating.cshtml, Website/Portals/_default/HotcakesViews/_default/Views/Products/_Rating.cshtml
Properly remove rating/review by configuration
=> Closes issue #200

DevSamples/MyWorkflow/MyWorkflow.cs, Libraries/Hotcakes.Commerce.Dnn/Workflow/DnnWorkflowFactory.cs
=> Added missing updates to completely resolve Issue #189

Website/DesktopModules/Hotcakes/Core/Scripts/hcc.views.js
=> Issue #169 - Fix moduleid Confict in hcc.views.js

Libraries/Hotcakes.Web/Validation/ValidationHelper.cs
updated regular expression  to allow  newer domain name variations to pass validation.
=> Issue #63 - Update Regular Expression For Checking Email

Website/DesktopModules/Hotcakes/Core/Api/Rest/ProductsHandler.cs
=> Allows created products to be searchable via the REST API

Website/DesktopModules/Hotcakes/ControlPanel/AdminControlBar.ascx, Website/DesktopModules/Hotcakes/ControlPanel/AdminControlBar.ascx.cs, Website/DesktopModules/Hotcakes/ControlPanel/App_LocalResources/AdminControlBar.ascx.resx, Website/DesktopModules/Hotcakes/Core/Admin/AppCode/MenuProvider.cs, Website/DesktopModules/Hotcakes/Core/Admin/Menu.xml
Issue no #109 Describe the problem that HCC uses the Static menu.xml file to load menu, Menu.xml Also has Permission Token that should not be skipped. in this pull request, I added a resource file, and add some method to localize string from menu.xml and also in `AdminControlBar.ascx`
=> Issue #109 - Localize Admin Bar Menu

.build/ModulePackage.targets, Libraries/Hotcakes.Commerce.Dnn/Providers/HccUrlRoutingModule.cs, Libraries/Hotcakes.Commerce.Dnn/Providers/ServiceRouteMapper.cs, Website/DesktopModules/Hotcakes/Core/HotcakesController.cs
=> Resolves issue #186

Libraries/Hotcakes.Commerce/Catalog/CatalogService.cs, Website/DesktopModules/Hotcakes/Core/Admin/Catalog/App_LocalResources/ProductTypePropertiesEdit.aspx.resx, Website/DesktopModules/Hotcakes/Core/Admin/Catalog/ProductTypePropertiesEdit.aspx, Website/DesktopModules/Hotcakes/Core/Admin/Catalog/ProductTypePropertiesEdit.aspx.cs, Website/DesktopModules/Hotcakes/Core/Admin/Catalog/ProductTypePropertiesEdit.aspx.designer.cs
=> Resolves #209

Website/DesktopModules/Hotcakes/Core/FileUpload.ashx.cs
=> Allowing file upload option for anonymous customers

Libraries/Hotcakes.Commerce/Accounts/StoreSettings.cs, Website/DesktopModules/Hotcakes/Core/Admin/Configuration/App_LocalResources/Orders.aspx.resx, Website/DesktopModules/Hotcakes/Core/Admin/Configuration/Orders.aspx, Website/DesktopModules/Hotcakes/Core/Admin/Configuration/Orders.aspx.cs, Website/DesktopModules/Hotcakes/Core/Admin/Configuration/Orders.aspx.designer.cs, Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.PaymentError.cs, Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs, Website/DesktopModules/Hotcakes/Core/Models/CheckoutViewModel.cs, Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/App_LocalResources/Controller.resx, Website/Portals/_default/HotcakesViews/_default/Views/Checkout/App_LocalResources/Controller.resx
=> Phone number requirement feature

Libraries/Hotcakes.Shipping.Ups/UPSService.cs
=> Adds UPS response to diagnostic logging

Libraries/Hotcakes.Commerce.Dnn/Marketing/Qualifications/UserIsInRole.cs
Filtered out expired user roles
=> Resolves #214

Website/DesktopModules/Hotcakes/Core/Admin/Catalog/App_LocalResources/ProductUpSellCrossSell.aspx.resx, Website/DesktopModules/Hotcakes/Core/Admin/Catalog/ProductUpSellCrossSell.aspx, Website/DesktopModules/Hotcakes/Core/Admin/Catalog/ProductUpSellCrossSell.aspx.cs, Website/DesktopModules/Hotcakes/Core/Controllers/ProductsController.cs, Website/DesktopModules/Hotcakes/Hotcakes.Modules.csproj
=> Not showing disabled products as related items

Libraries/Hotcakes.Commerce/Catalog/CatalogImport.cs
=> Assigns imported images to imported products

Libraries/Hotcakes.Commerce/Hotcakes.Commerce.csproj, Libraries/Hotcakes.Commerce/Utilities/FileSystemHelper.cs, Website/DesktopModules/Hotcakes/Core/ClearUploadTempFilesJob.cs, Website/DesktopModules/Hotcakes/Core/HotcakesController.cs, Website/DesktopModules/Hotcakes/Hotcakes.Modules.csproj
=> Adds a scheduled task to clear temp files

Website/DesktopModules/Hotcakes/Core/Admin/admin.css
display: inline-block instead of inline
=> Fixes #288

Libraries/Hotcakes.Commerce/Search/ProductSearchHelper.cs, Libraries/Hotcakes.Commerce/Search/SqlSearchProvider.cs
=> Resolves sort order issue with displayed facets

Website/DesktopModules/Hotcakes/Core/Admin/AppCode/MenuProvider.cs
=> Resolves #294

Website/DesktopModules/Hotcakes/Core/Controllers/CategoryController.cs, Website/web.config
=> Closes #313

Libraries/Hotcakes.Commerce.Dnn/Providers/ProductsSitemapProvider.cs
Fixes HotcakesCommerce/hotcakes-commerce-core#305
=> Provide Sitemap-URLs of active products only 

Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs
=> Remove GB from EU VAT rules - fixes #356

Website/DesktopModules/Hotcakes/Core/Controllers/ProductsController.cs
Ticket #372
Issue happen because Quantity is NULL.
Set default Quantity to 1 when using the user-supplied price
=> Fix #372 - User Supplied Price Minimum Quantity Error

Website/DesktopModules/Hotcakes/ExtensionUrlProvider/HccExtensionUrlProvider.cs
=> Fix Not add Culture Code in URL Provider

Website/DesktopModules/Hotcakes/Core/Admin/Catalog/ProductTypePropertiesEdit.aspx.cs
=> ProductPropertyChoiceId should not set as local variable.

Website/DesktopModules/Hotcakes/Core/Admin/Admin.master
=> Resolves #401

Libraries/Hotcakes.Commerce/Catalog/CatalogImport.cs, Website/DesktopModules/Hotcakes/Core/Admin/Catalog/ProductSharedChoices.aspx.cs
Related issue: #379
Import will not include Product shared options Price & Weight.
After import administrator need to update Shared Options price & weight.
=> Fix duplicate Product Shared Option on Import products

Website/DesktopModules/Hotcakes/Core/HotcakesController.cs, Website/DesktopModules/Hotcakes/Providers/DataProviders/SqlDataProvider/Uninstall.SqlDataProvider
Update Uninstall Method in HotcakesController and fix SqlDataProvider, to completely remove Hotcakes folder under DesktopModule, dll files & HCC Table.
=> Uninstall Leaves Artifacts

DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Views/Checkout/_CreditCardInput.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Views/Checkout/_CreditCardInput.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/Checkout/_CreditCardInput.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/Views/Checkout/_CreditCardInput.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_CreditCardInput.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_CreditCardInput.cshtml, Website/Portals/_default/HotcakesViews/Bootstrap4/Views/Checkout/_CreditCardInput.cshtml, Website/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_CreditCardInput.cshtml, Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_CreditCardInput.cshtml, Website/Portals/_default/HotcakesViews/_default-Legacy/Views/Checkout/_CreditCardInput.cshtml, Website/Portals/_default/HotcakesViews/_default/Views/Checkout/_CreditCardInput.cshtml
Update the remaining partial views
=> Not autocomplete credit cards

Website/DesktopModules/Hotcakes/ProductGrid/Settings.ascx.cs
Fixed #419 SI: Product Grid Doesn't Allow Products to be Deleted
=> Changed-var-key-value-reference

Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs
Fixes #436
CheckoutController.cs:
- Updated CurrentCart null condition location.
=> Issue #436 - SI: CheckoutController will Occasionally throw a NULL Ref Exception

DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Scripts/Checkout.js, DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Views/Checkout/_CreditCardInput.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Scripts/Checkout.js, DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Views/Checkout/_CreditCardInput.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Scripts/Checkout.js, DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/Checkout/_CreditCardInput.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Scripts/Checkout.js, DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_CreditCardInput.cshtml, DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Scripts/Checkout.js, DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_CreditCardInput.cshtml, Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs, Website/Portals/_default/HotcakesViews/Bootstrap4/Scripts/Checkout.js, Website/Portals/_default/HotcakesViews/Bootstrap4/Views/Checkout/_CreditCardInput.cshtml, Website/Portals/_default/HotcakesViews/Porto5/Scripts/Checkout.js, Website/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_CreditCardInput.cshtml, Website/Portals/_default/HotcakesViews/SocialSpokes/Scripts/Checkout.js, Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_CreditCardInput.cshtml, Website/Portals/_default/HotcakesViews/_default-Legacy/Scripts/Checkout.js, Website/Portals/_default/HotcakesViews/_default-Legacy/Views/Checkout/_CreditCardInput.cshtml, Website/Portals/_default/HotcakesViews/_default/Scripts/Checkout.js, Website/Portals/_default/HotcakesViews/_default/Views/Checkout/_CreditCardInput.cshtml
Fix the validation issue in POST request 
Update all views to insert the new hidden property for StripePublicKey
Update the checkout.js file for all views to validate by the nameOnCard field
=> Stripe checkout changes

Build.proj, CommonAssemblyInfo.cs, GlobalAssemblyInfo.cs, Website/DesktopModules/Hotcakes/Hotcakes.dnn, Website/DesktopModules/Hotcakes/Hotcakes_Symbols.dnn, Website/DesktopModules/Hotcakes/ReleaseNotes.txt
=> Updated version & release notes

Libraries/Hotcakes.PaypalWebServices/RestPaypalApi.cs, Website/DesktopModules/Hotcakes/Hotcakes.dnn
After installing release 03.08.01, attempting to configure the store with default settings resulted in the following error:
To address the issue, I initially installed the latest version on a clean DNN structure and confirmed the problem's existence. Subsequently, I proceeded to debug the code to pinpoint the error.
I managed to locate the error in the `CreateTabFromTemplate` method within the `PageUtils.cs` class, specifically at line 98:
```csharp
tab = TabController.DeserializeTab(tabNode, tab, portalSettings.PortalId,
PortalTemplateModuleAction.Merge);
```
This method belonged to the DNN class `DotNetNuke.Entities.Tabs.TabController`, which couldn't be debugged or modified. Considering that the previous version of the code worked correctly, I investigated the modified files in this …
=> Fix setup wizard

Build.proj, CommonAssemblyInfo.cs, Website/DesktopModules/Hotcakes/Core/Admin/SetupWizard/App_LocalResources/Step0Dashboard.ascx.resx, Website/DesktopModules/Hotcakes/Hotcakes.dnn, Website/DesktopModules/Hotcakes/Hotcakes_Symbols.dnn, Website/DesktopModules/Hotcakes/License.txt, Website/DesktopModules/Hotcakes/ReleaseNotes.txt
=> Syncing dev and main

Build.proj, CommonAssemblyInfo.cs, GlobalAssemblyInfo.cs, Libraries/Hotcakes.Commerce.Dnn/App.Config, Libraries/Hotcakes.Commerce.NoCms/App.config, Libraries/Hotcakes.Commerce/Hotcakes.Commerce.csproj, Libraries/Hotcakes.Commerce/packages.config, Website/DesktopModules/Hotcakes/Hotcakes.dnn, Website/DesktopModules/Hotcakes/Hotcakes_Symbols.dnn, Website/DesktopModules/Hotcakes/License.txt, Website/DesktopModules/Hotcakes/ReleaseNotes.txt, Website/DesktopModules/Hotcakes/web.config
Syncing branches for the 3.8.2 release
=> Tasks/release 03.08.02

Build.proj, CommonAssemblyInfo.cs, GlobalAssemblyInfo.cs, Libraries/Hotcakes.Commerce.Dnn/App.Config, Libraries/Hotcakes.Commerce.NoCms/App.config, Libraries/Hotcakes.Commerce/Hotcakes.Commerce.csproj, Libraries/Hotcakes.Commerce/packages.config, Libraries/Hotcakes.PaypalWebServices/RestPaypalApi.cs, Website/DesktopModules/Hotcakes/Core/Admin/SetupWizard/App_LocalResources/Step0Dashboard.ascx.resx, Website/DesktopModules/Hotcakes/Hotcakes.dnn, Website/DesktopModules/Hotcakes/Hotcakes_Symbols.dnn, Website/DesktopModules/Hotcakes/License.txt, Website/DesktopModules/Hotcakes/ReleaseNotes.txt, Website/DesktopModules/Hotcakes/web.config, Website/Portals/_default/HotcakesViews/Bootstrap4/Views/Search/Index.cshtml, Website/Portals/_default/HotcakesViews/Porto5/Views/Search/Index.cshtml, Website/Portals/_default/HotcakesViews/_default/Views/Search/Index.cshtml
Syncing branches for the 3.8.2 release
=> Syncing branches

Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs
Fixes # [508 Problems completing the order when the RequiresUniqueEmail option is activated](https://github.com/HotcakesCommerce/hotcakes-commerce-core/issues/508)
This PR resolves the issue where guest users encounter an error during checkout when the `requiresUniqueEmail="true" `option is enabled in DNN. Changes include:
- Modified the logic to check for existing email accounts without interrupting the guest checkout process.
- Ensured a new user is created in DNN if no account exists for the email, and the order completes successfully.
- Tested in DNN 09.13.04 with Hotcakes 03.08.02.
- Verified the checkout process for both registered and guest users.
- Simulated scenarios with unique and duplicate email addresses to confirm the correct behavior.
**Steps:**
1. Enabled …
=> Fix Issue 508

Website/DesktopModules/Hotcakes/Core/Admin/Orders/App_LocalResources/CreateOrder.aspx.resx, Website/DesktopModules/Hotcakes/Core/Admin/Orders/CreateOrder.aspx, Website/DesktopModules/Hotcakes/Core/Admin/Orders/CreateOrder.aspx.cs
Fixes #451 
A table has been created in the view and methods to display customer results when the names contain the search keyword. Previously, this was confusing, as the system only displayed the total number of customers found, but not their names. In addition, the method required the search to be more specific in order to display and select the customer. Now, with this improvement, the customer names are clearly listed in the table, and there is a "Select Customer" button to select them if desired.
Create multiple customers with the same name beginning to perform the search.
Also perform the search with a more unique name.
=> HCC: Edit Order > FInd Customer bug

Libraries/Hotcakes.Commerce/Data/EF/HccDbContext.edmx
Mapping error for the **UpchargeUnit** property of **Products** in the **HCC DbContext**.
This PR fixes the mapping error for the **UpchargeUnit** property of **Product** in the **HCC DbContext**, which caused an error during checkout when a product did not have the **IsFeatured** option enabled.
The update was tested on a clean **DNN 09.13.07** installation and the **PW site backup**, and everything worked as expected.
=> SI: Update HccDbContext.edmx

Website/DesktopModules/Hotcakes/Core/Admin/Orders/CreateOrder.aspx, Website/DesktopModules/Hotcakes/Core/Admin/Orders/CreateOrder.aspx.designer.cs
Fixes #104 
This update contains changes to fix the usability issue with the Bill to Same Address checkbox.
Tested in a local environment with the latest version of DNN and HCC available
=> Fix Billing Address Usability Issue
