.editorconfig
Libraries/Hotcakes.Commerce/SessionManager.cs
Libraries/Hotcakes.Web/Cookies.cs

Fixes #20.
Removed unnecessary and potentially damaging browser capability checks. Browsers erroneously detected as not supporting cookies could not retain shopping cart state.

Issue #20 - Items cannot be added to cart if .NET incorrectly detects browser cookie capability

---

.gitignore
Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.PaymentError.cs

Since the PaymentError action will always be called after the order has been created and the cart cookie has been cleared I have removed the CurrentCart check since it will always return null.

Issues/issue 120 - Failed Checkout Returns to Cart

---

Website/DesktopModules/Hotcakes/Core/Controllers/CategoryController.cs

I have checked with null reference object.

CI: CategoryViewer - DrillDown view error when no category is set #101

---

Libraries/Hotcakes.Commerce/BusinessRules/OrderTasks/StartPaypalExpressCheckout.cs
Libraries/Hotcakes.Commerce/Payment/Methods/PaypalExpress.cs

To fulfill this requirements two major changes are done in two files , which are as below
1. StartPaypalExpressCheckout.cs
2. PaypalExpress.cs 
in these files an condition is included to verify "Authorization" or "Sale" option from Paypal Express Settings.

SI: PayPal Express Authorize Setting Not Creating Authorizations #50

---

Libraries/Hotcakes.Commerce.Dnn/Workflow/DnnWorkflowFactory.cs

MembershipTask() has been moved from LoadProcessNewOrderTasks() to LoadProcessNewOrderAfterPaymentTasks() to avoid assigning user accounts to failed payment orders.

Issue #189 - Assign membership only after successful payment

---

Website/DesktopModules/Hotcakes/Core/Models/Json/SingleProductJsonModel.cs

1- Add `category viewer` module to a page
2- set drill Down as a view 
3- display price of products does not include currency symbol and other adjustment

Issue #173 - Display Price visibility issue in DrillDown View

---

Website/DesktopModules/Hotcakes/Core/Admin/Catalog/Categories.js

The parent object was losing it's hieght when the child objects were being moved.  This corrects it by setting forcePlaceholderSize to true and the tolerance to 'pointer'.

(Issue #193)  Category Sorting Not Working in Admin

---

Website/DesktopModules/Hotcakes/Core/HotcakesController.cs

No longer adding a Host page & removing existing ones

---

Libraries/Hotcakes.Commerce.Dnn/Providers/ProductsSitemapProvider.cs

Fix for #269 
Localizes HccRequestContext in the SitemapProvider for localized TabIDs

Localization of Sitemaps - fixes #269

---

Libraries/Hotcakes.Commerce/BusinessRules/OrderTasks/ReceiveCreditCards.cs

Resolves #345 by using the OrderTaskContext.Order.OrderNumber as a fallback in case the OrderNumber on the Transaction object is empty

Fixes Transaction.Items is null first time ProcessTransaction is called

---

Website/Portals/_default/HotcakesViews/_default/Scripts/AffiliateDashboard.js
Website/Portals/_default/HotcakesViews/_default/Views/AffiliateDashboard/_UrlBuilder.cshtml

Fixes #346 
The ajax request was reloading the page, preventing the user from being able to see and use the urls that were generated. This fix will resolve that issue in the default template to allow to see and use the url that is generated and copy it to their clipboard.

Fixes #346

---

Website/DesktopModules/Hotcakes/Core/Controllers/CartController.cs

Fixes #350 
Checks the RedirectResult from the HandleActionParams() and if it's something other than the Cart page, it redirects, otherwise it continues with loading the Shopping Cart

Fixes #350 - RedirectToCheckout param not working

---

Libraries/Hotcakes.Commerce/Orders/OrderPaymentManager.cs

A Paypal hold could fail due to end user's lack of funds or linked account. If this happens, the Paypal Express Hold should return a fail, not a success.

Paypal Express Hold Authorization issue

---

Website/DesktopModules/Hotcakes/Core/Controllers/PayPalExpressCheckoutController.cs

Resolves PayPal Express redirect - Issues #368

---

DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Views/AffiliateRegistration/Index.cshtml
DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Views/AffiliateRegistration/Index.cshtml
DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/AffiliateRegistration/Index.cshtml
DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Views/AffiliateRegistration/Index.cshtml
DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/AffiliateRegistration/Index.cshtml
Libraries/Hotcakes.Shipping/USPSAddressProvider.cs
Website/DesktopModules/Hotcakes/Core/Models/AffiliateViewModel.cs
Website/Portals/_default/HotcakesViews/Bootstrap4/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
Website/Portals/_default/HotcakesViews/Bootstrap4/Views/AffiliateRegistration/Index.cshtml
Website/Portals/_default/HotcakesViews/Porto5/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
Website/Portals/_default/HotcakesViews/Porto5/Views/AffiliateRegistration/Index.cshtml
Website/Portals/_default/HotcakesViews/SocialSpokes/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
Website/Portals/_default/HotcakesViews/SocialSpokes/Views/AffiliateRegistration/Index.cshtml
Website/Portals/_default/HotcakesViews/_default-Legacy/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
Website/Portals/_default/HotcakesViews/_default-Legacy/Views/AffiliateRegistration/Index.cshtml
Website/Portals/_default/HotcakesViews/_default/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
Website/Portals/_default/HotcakesViews/_default/Views/AffiliateRegistration/Index.cshtml

Fix #292 include :
- Javascript issue due missing validation for Confirm Terms
- Term Popup show nothing event if affiliate agreement terms been fill in
Tested on :
- Default Theme
- Porto Theme

Fix #292 - Affiliate & Category (drilldown) views don't work

---

Libraries/Hotcakes.Shipping.Ups/UPSService.cs

Issue #363 
Ups Api url been change into https://onlinetools.ups.com/

Change UPS Api Url

---

Libraries/Hotcakes.Commerce/Catalog/ProductRepository.cs
Website/DesktopModules/Hotcakes/Hotcakes.dnn

Removed unnecessary assembly reference within the manifest.
Fixed #412

Fix Installer generated by HCC (BUG)

---

Libraries/Hotcakes.Commerce/Catalog/ProductRepository.cs

Optimization of the FindManyWithCache method.
Reduction of multiple traversals via foreach to input parameters. A reduction to only one was made.
The call to the FindMany method was changed by a call to the Find method that already inside it adds the product to the cache storage

Update FindManyWithCache Method

---

Libraries/Hotcakes.Web/Validation/ValidationHelper.cs

Updated the Regex method that validates the email address when performing the Checkout, allowing the address to contain the underscore character in the address. Only allowed in the part of the email before the @domain... The Regex method that DNN uses when validating the email record allows this character. #421

Updated the Regex method. Issue #421 Fixed 

---

Build.proj
build.bat

Modifying the Build.proj file and declaring C# 10.0 as the language.
Modify the build.bat file and change the MSBuild reference to the one found in VS2022.

Update HCC to use MSBuild Version=15.1.0.0 & C# 10.0

---

Libraries/Hotcakes.Commerce.Dnn/App.Config
Website/DesktopModules/Hotcakes/Hotcakes.Modules.csproj
Website/DesktopModules/Hotcakes/packages.config
Website/DesktopModules/Hotcakes/web.config

The PR aims to correct all the conflicts that exist between the different versions of assembly references.
>System.Web.Mvc - v4.0.0.0, v5.1.0.0, v5.2.3.0.
>NewtonSoft.Json - v7.0.0.0, v10.0.0.0.
Changes made
___________________________________________________________________________________________________________________________________
- Update hotcakes-commerce-core\Website\DesktopModules\Hotcakes\web.config
- Update hotcakes-commerce-core\Website\DesktopModules\Hotcakes\packages.config
- Update hotcakes-commerce-core\Website\DesktopModules\Hotcakes\Hotcakes.Modules.csproj
- Update hotcakes-commerce-core\Libraries\Hotcakes.Commerce.Dnn\App.Config
Close #333

Hcc resolve dll version warnings

---

Libraries/Hotcakes.Commerce.Dnn/Hotcakes.Commerce.Dnn.csproj
Libraries/Hotcakes.Commerce.Dnn/packages.config
Libraries/Hotcakes.Commerce.NoCms/Hotcakes.Commerce.NoCms.csproj
Libraries/Hotcakes.Commerce.NoCms/packages.config
Libraries/Hotcakes.Commerce/Hotcakes.Commerce.csproj
Libraries/Hotcakes.Commerce/packages.config
Libraries/Hotcakes.Web/Hotcakes.Web.csproj
Libraries/Hotcakes.Web/packages.config
Website/DesktopModules/Hotcakes/Hotcakes.Modules.csproj
Website/DesktopModules/Hotcakes/packages.config

**Description of PR...**
The PR aims to migrate the version of the HCC EntityFramework from the current version 6.1.1 to version 6.4.4.
EF 6.4.0
The EF 6.4.0 runtime was released to NuGet in December 2019. The primary goal of EF 6.4 is to polish the features and scenarios that was delivered in EF 6.3. See list of important fixes on GitHub.
https://github.com/dotnet/ef6/milestone/14?closed=1
**Changes made**
___________________________________________________________________________________________________________________________________
- Update Hotcakes.Commerce.Dnn (.csproj file & packages.config)
- Update Hotcakes.Commerce.NoCms (.csproj file & packages.config)
- Update Hotcakes.Commerce (.csproj file & packages.config)
- Update Hotcakes.Web (.csproj file & packages.config)
- Update …

Hcc Update Entity Framework

---

Libraries/Hotcakes.Commerce/HccRequestContext.cs

Fixes # https://github.com/HotcakesCommerce/hotcakes-commerce-core/issues/454 Abandoned Cart Email throwing exception
The bug was occurring due to a null reference error when attempting to access the HccRequestContext object. The previous code did not properly initialize the _current object, leading to the null reference.
To resolve this issue, I added a check to ensure that the HttpContext.Current is not null. If it is null, I initialize the _current object as a new HccRequestContext instance. This ensures that the object is properly initialized and prevents the null reference error from occurring.
I have thoroughly tested the changes in various scenarios, and the bug no longer occurs. The application now correctly handles the HccRequestContext object, ensuring smooth execution without …

Issue #454 - Fix Abandoned Cart Email Bug

---

Website/DesktopModules/Hotcakes/ProductGrid/Settings.ascx.cs

Fixes #474 
The problem was caused by data inconsistency between the dictionary containing the products loaded form the setting and the information stored inside of the grid view object. I solve it by adding a extra call to the LoadItems method to force the grid to update before the product is deleted.
Locally in my development environment

SI: Updating rgProducts before deleting

---

Libraries/Hotcakes.PaypalWebServices/RestPaypalApi.cs

Fixes # [479 SI: INVALID_PARAMETER_SYNTAX PayPal Payments Pro](https://github.com/HotcakesCommerce/hotcakes-commerce-core/issues/479)
To solve the issue, add a method called formatAmount to cleanse (remove comma or space separators from) the order amounts before they are sent to the PayPal API.  Since that API doesn't accept values with separators such as commas or spaces.
To test that the update fixed the issue, I created a clean DNN solution in version 09.13.00, compiled it, and generated a Hotcakes installer with the applied changes. Then, I conducted the initial store setup. I added a product with an amount greater than 999.00, specifically 1200.00.
Afterwards, I configured the payment methods, choosing PayPal, and updated the Sandbox Mode settings by entering the API Client Id and …

Fix Issues 479 INVALID_PARAMETER_SYNTAX PayPal Payments Pro

---

Libraries/Hotcakes.PaypalWebServices/RestPaypalApi.cs

Fixes # [Issues 484](https://github.com/HotcakesCommerce/hotcakes-commerce-core/issues/484)
The `formatAmount `method was applied to the amounts within the `doDirectCheckout`, `CaptureAuthorizedOrder`, and `CapturesRefund `methods in `RestPaypalApi` service  to adjust the currency format according to PayPal API requirements.
The HCC module was installed with the changes made, providing a clean DNN solution. The PayPal payment method was set up, and multiple tests were conducted to ensure that everything worked correctly.

Fix PayPal CheckOut Error

---

Libraries/Hotcakes.Commerce/Catalog/VariantRepository.cs

When multiple stores exist, and you attempt to add a variant to a product, it is not currently filtered by StoreId. It gives an error message about the SKU already existing even though the SKU doesn't exist in the current store. 
This adds a stored check based on the current context.
No issue currently exists
Gets the current store id from the context and filters what variants we are looking for by the store id.

Check Store ID when Checking for Duplicate Variants

---

Libraries/Hotcakes.Payment/CardData.cs
Libraries/Hotcakes.Payment/Gateways/StripeProcessor.cs
Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs
Website/DesktopModules/Hotcakes/Core/Models/CheckoutViewModel.cs
Website/Portals/_default/HotcakesViews/Bootstrap4/Scripts/Checkout.js
Website/Portals/_default/HotcakesViews/Bootstrap4/Views/Checkout/App_LocalResources/Controller.resx
Website/Portals/_default/HotcakesViews/Bootstrap4/Views/Checkout/_CreditCardInput.cshtml
Website/Portals/_default/HotcakesViews/Porto5/Scripts/Checkout.js
Website/Portals/_default/HotcakesViews/Porto5/Views/Checkout/App_LocalResources/Controller.resx
Website/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_CreditCardInput.cshtml
Website/Portals/_default/HotcakesViews/SocialSpokes/Scripts/Checkout.js
Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/App_LocalResources/Controller.resx
Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_CreditCardInput.cshtml
Website/Portals/_default/HotcakesViews/_default-Legacy/Scripts/Checkout.js
Website/Portals/_default/HotcakesViews/_default-Legacy/Views/Checkout/App_LocalResources/Controller.resx
Website/Portals/_default/HotcakesViews/_default-Legacy/Views/Checkout/_CreditCardInput.cshtml
Website/Portals/_default/HotcakesViews/_default/Scripts/Checkout.js
Website/Portals/_default/HotcakesViews/_default/Views/Checkout/App_LocalResources/Controller.resx
Website/Portals/_default/HotcakesViews/_default/Views/Checkout/_CreditCardInput.cshtml

Fixes # [485](https://github.com/HotcakesCommerce/hotcakes-commerce-core/issues/485)
In this PR, the following updates were made:
- **Stripe.js Integration**: Stripe.js was incorporated to securely capture customer card details and obtain the payment method from the front-end, in compliance with Stripe's security policies.
- **Modifications to HCC's Main Viewsets**: Adjustments were made to HCC's main viewsets to facilitate integration with Stripe.js.
- **Validation Updates**: Validations were updated on both the client and server sides for cases where the payment gateway is Stripe.
Multiple tests were conducted in my local environment using a clean installation of DNN 9.13.3, and everything worked as expected.

Update stripe api

---

Website/DesktopModules/Hotcakes/Core/Admin/Catalog/Products_Edit_Inventory.aspx.cs

Fixes #510 
This fix addresses an issue where products set to the inventory mode "When Out of Stock, Show but Don't Allow Purchases" disappear from the Category Drilldown view after clearing the HCC cache.  
The implemented solution automatically clears the store cache after saving changes to the inventory, ensuring that the changes are reflected correctly in the view.
Tested in DNN 09.13.06 and HCC 03.09.00
https://app.screencast.com/26FO0pcWlSpQL

Fix Category Drilldown View to respect Inventory Mode settings

---

Website/DesktopModules/Hotcakes/Core/Admin/Controls/DateRangePicker.ascx
Website/DesktopModules/Hotcakes/Core/Admin/Controls/DateRangePicker.ascx.cs
Website/DesktopModules/Hotcakes/Core/Admin/Reports/Summary Report/View.aspx

Fixes #300 
This pull request updates the date pickers in HC Admin Reports → Custom Date Range to dynamically use the correct date format based on CurrentCulture. Previously, date pickers were hardcoded to en-US (MM/dd/yyyy), which caused inconsistencies and errors when using the en-GB locale (dd/MM/yyyy).
- Now, flatpickr dynamically adjusts to the date format based on CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern.
- The .NET date format is automatically converted to flatpickr-compatible format.
- Ensures that all affected reports use the correct localized format without requiring manual configuration.
- Updated C# backend to ensure consistent parsing of date values based on the current culture
I tested locally and confirmed correct behavior in en-GB (dd/MM/yyyy).
and …

Fixes incorrect date format in HC Admin "Reports" custom date range pickers

---

Website/DesktopModules/Hotcakes/Core/Admin/Catalog/App_LocalResources/ProductTypeProperties.aspx.resx
Website/DesktopModules/Hotcakes/Core/Admin/Catalog/ProductTypeProperties.aspx.cs

Fixes #187 
Added a change to the dgList_DeleteCommand method to ensure that when a product type property value is deleted, a reference check is performed, if this value is currently assigned to a product it does not allow deletion and displays an error message "This property is assigned to a product and cannot be deleted."
I tested locally

Product type property deleting issue
